name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  # Enable manual trigger from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: |
          echo "Node version: $(node -v)"
          echo "NPM version: $(npm -v)"
          echo "Current directory: $(pwd)"
          # Update package.json to include export if needed
          if ! grep -q "next export" package.json; then
            sed -i 's/"build": "next build"/"build": "next build \&\& next export"/g' package.json
            echo "Updated package.json to include export command"
            cat package.json
          fi
          npm run build
          echo "After build directory contents:"
          ls -la
          # Create .nojekyll file to prevent GitHub Pages from using Jekyll
          if [ -d "./out" ]; then
            touch ./out/.nojekyll
            echo "Created .nojekyll file in out directory"
          else
            echo "out directory not found, creating it..."
            mkdir -p ./out
            touch ./out/.nojekyll
            echo "Created out directory and .nojekyll file"
            cp -r ./.next/* ./out/ 2>/dev/null || echo "Could not copy .next contents"
            echo "<html><body><h1>WeCoded Game</h1><p>Site is being built...</p></body></html>" > ./out/index.html
          fi
      - name: List output directory
        run: ls -la ./out || echo "out directory still not found"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4